"""
Django settings for mensa_member_connect_backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from logging.handlers import TimedRotatingFileHandler
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Define log directory
LOG_DIR = BASE_DIR / "logs"

# Ensure the logs directory exists
os.makedirs(LOG_DIR, exist_ok=True)

# Load environment variables from .env explicitly
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-23)@vm5vpch=0%*d(p^x092cfxl(hrov=3m1wep2)ll7@g5(@x"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS", "").split(",") if os.getenv("ALLOWED_HOSTS") else ["*"]
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",  # Django REST Framework
    "rest_framework_simplejwt",  # JWT Authentication
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",  # For cross-origin requests
    "whitenoise.runserver_nostatic",  # Optional helper for static serving in dev
    "mensa_member_connect",
]

MIDDLEWARE = [
    # CORS — must come before CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",
    # Security and static file handling
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Core Django middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# allow your dev frontend
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
# ]

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False") == "True"
CORS_ALLOWED_ORIGINS = (
    os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if os.getenv("CORS_ALLOWED_ORIGINS")
    else []
)

AUTH_USER_MODEL = "mensa_member_connect.CustomUser"

ROOT_URLCONF = "mensa_member_connect_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mensa_member_connect_backend.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=18),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database Configuration
# Support both Railway's DATABASE_URL and individual environment variables
if "DATABASE_URL" in os.environ:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "postgres"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "OPTIONS": {
                "sslmode": os.getenv(
                    "DB_SSLMODE", "prefer"
                ),  # 'require' for remote, 'prefer' for local
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
#     {
#         "NAME": "mensa_member_connect.validators.custom_user_validators.StrongPasswordValidator"
#     },
# ]

AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ==============================
# EMAIL CONFIGURATION
# ==============================
# Django email settings for sending system messages, verification emails,
# and password resets via Mailgun SMTP.
# Reference: https://docs.djangoproject.com/en/5.1/topics/email/
# Mailgun docs: https://help.mailgun.com/hc/en-us/articles/203380100

# - Mailgun requires verified sending domains and proper DNS (SPF, DKIM, MX).
# - Use port 587 with TLS unless you have a firewall issue — ports 25 or 2525 also work.
# - Port 465 requires EMAIL_USE_SSL=True and EMAIL_USE_TLS=False.
# - Keep EMAIL_HOST_PASSWORD secure — store it in environment variables or a secret vault.
# - For local testing, you can switch to 'django.core.mail.backends.console.EmailBackend'

# Default sender address for outgoing emails
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@namme.us")

# Backend to handle email delivery
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)

# Mailgun SMTP host and ports:
# 25, 587, and 2525 = STARTTLS (recommended)
# 465 = SSL/TLS (legacy)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.mailgun.org")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))  # use 587 for STARTTLS

# Mailgun SMTP credentials
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "postmaster@namme.us")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

# Security settings
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() in ("1", "true", "yes")

# Optional settings
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", 10))
EMAIL_SUBJECT_PREFIX = os.environ.get("EMAIL_SUBJECT_PREFIX", "[MENSA] ")

# Admin and Manager notifications
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", "admin@namme.us")
ADMINS = [
    ("Admin", os.environ.get("ADMIN_EMAIL", "admin@namme.us")),
]
MANAGERS = ADMINS

# ==============================
# LOGGING CONFIGURATION
# ==============================
# Django logging setup that reads LOG_LEVEL from .env.
# Logs are stored in logs/django.log (ensure the 'logs/' directory exists).
# Adjust log level per environment: DEBUG (dev), INFO (staging), WARNING (prod).
LOG_LEVEL = os.getenv("LOG_LEVEL", "WARNING")  # Default to WARNING if not set

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "django.log"),
            "when": "midnight",  # Rotate logs at midnight
            "interval": 1,  # Rotate every 1 day
            "backupCount": 10,  # Keep the last 10 days of logs
            "formatter": "verbose",
            "delay": True,
            # When the RotatingFileHandler is used without the delay option, it opens the log file
            # as soon as the logging configuration is loaded, even before any logging takes place.
            # This can result in the file being locked for the entire process, preventing log
            # rotation (or renaming of the log file) because the file is still being held open by
            # the logging handler.
            # By setting delay: True, the RotatingFileHandler delays the opening of the log file
            # until the first log message is written. This means the file is not immediately locked
            # by the handler when the application starts, and it allows log rotation to proceed
            # without any issues. Essentially, it avoids any conflicts between the log rotation
            # process and any other process or thread that may want to access the log file
            # (like Django’s development server, which could be holding the file open).
        },
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "mensa_member_connect": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,  # Prevents double logging
        },
        # Log database queries
        "django.db.backends": {
            "level": os.getenv(
                "DB_LOG_LEVEL", LOG_LEVEL
            ),  # Use DB_LOG_LEVEL if set, otherwise fallback
            "handlers": ["file", "console"],  # Log to both file and console
            "propagate": False,  # Prevent it from propagating to the root logger
        },
    },
    "root": {
        "handlers": ["file", "console"],
        "level": LOG_LEVEL,
    },
}
