# Generated by Django 5.1.3 on 2025-09-23 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminaction',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='adminaction',
            old_name='target_user_id',
            new_name='target_user',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='expert_id',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='seeker_id',
            new_name='seeker',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='industry_id',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='expert_id',
        ),
        migrations.AddField(
            model_name='expert',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='mensa_member_connect.industry'),
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertise',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='mensa_member_connect.expert'),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='local_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mensa_member_connect.localgroup'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
