# Generated by Django 5.1.3 on 2025-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0002_rename_admin_id_adminaction_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='local_group_id',
            new_name='local_group',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='member', max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='active', max_length=24),
        ),
    ]
