# Generated by Django 5.1.3 on 2025-10-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0003_rename_local_group_id_customuser_local_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability_status',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='background',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_experts', to='mensa_member_connect.industry'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_contact_info',
            field=models.BooleanField(default=False),
        ),
    ]
