# Generated by Django 5.1.3 on 2025-10-21 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0004_customuser_availability_status_customuser_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='expert',
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to=settings.AUTH_USER_MODEL),
        ),
    ]
