# Generated by Django 5.1.3 on 2025-10-21 23:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0005_remove_expertise_expert_expertise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='localgroup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='localgroup',
            name='state',
        ),
        migrations.AddField(
            model_name='localgroup',
            name='group_number',
            field=models.CharField(default='000', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Enter a 3-digit number')]),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Expert',
        ),
    ]
