# Generated by Django 5.1.3 on 2025-10-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0006_alter_connectionrequest_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='area_of_expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expertises', to='mensa_member_connect.industry'),
        ),
    ]
