# Generated by Django 5.1.3 on 2025-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0007_expertise_area_of_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
