# Generated by Django 5.1.3 on 2025-11-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0008_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='pending', max_length=24),
        ),
    ]
