# Generated by Django 5.1.3 on 2025-11-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0009_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='preferred_contact_method',
            field=models.CharField(blank=True, help_text='Preferred contact method: email, phone, video_call, in_person, other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
