# Generated by Django 5.1.3 on 2025-11-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensa_member_connect', '0010_connectionrequest_preferred_contact_method_and_more'),
        ('mensa_member_connect', '0010_remove_customuser_username_alter_customuser_email_and_more'),
    ]

    operations = [
    ]
